[package]
name = "emstudio-worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
emstudio-domain = { path = "../domain" }
rmp-serde.workspace = true
serde.workspace = true
serde_json.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = [
    "DedicatedWorkerGlobalScope",
    "MessageEvent",
    "console",
] }
js-sys.workspace = true
console_error_panic_hook.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
emstudio-solver = { path = "../solver" }
