[package]
name = "emstudio-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
eframe.workspace = true
egui.workspace = true
egui_dock.workspace = true
emstudio-components = { path = "../components" }
emstudio-domain = { path = "../domain" }
emstudio-infra = { path = "../infra" }
emstudio-render = { path = "../render" }
