use crate::error::AnsysExchangeError;
use crate::model::{AnsysDesignKind, AnsysProject};

#[cfg(not(target_arch = "wasm32"))]
use std::path::Path;

pub fn export_manifest_json_string(project: &AnsysProject) -> Result<String, AnsysExchangeError> {
    serde_json::to_string_pretty(project).map_err(|e| AnsysExchangeError::Json(e.to_string()))
}

pub fn export_pyaedt_script(project: &AnsysProject) -> String {
    let mut out = String::new();

    out.push_str("# Auto-generated by emstudio-ansys-exchange\n");
    out.push_str("from ansys.aedt.core import Hfss, Q3d\n\n");
    out.push_str("non_graphical = True\n");
    out.push_str("version = \"2025.2\"\n\n");

    for (idx, d) in project.designs.iter().enumerate() {
        let var_name = format!("design_{}", idx + 1);
        let ctor = match d.kind {
            AnsysDesignKind::Hfss => "Hfss",
            AnsysDesignKind::Q3d => "Q3d",
        };
        out.push_str(&format!(
            "{} = {}(projectname=\"{}\", designname=\"{}\", solution_type=\"{}\", specified_version=version, non_graphical=non_graphical, new_desktop_session=False)\n",
            var_name,
            ctor,
            escape_py_string(&project.name),
            escape_py_string(&d.name),
            d.solution_type.as_ansys_label()
        ));

        for (key, val) in &d.variables {
            out.push_str(&format!(
                "{}.variable_manager.set_variable(\"{}\", \"{}\")\n",
                var_name,
                escape_py_string(key),
                escape_py_string(val)
            ));
        }

        out.push('\n');
    }

    out.push_str("print(\"Export completed.\")\n");
    out
}

#[cfg(not(target_arch = "wasm32"))]
pub fn export_pyaedt_script_file(
    project: &AnsysProject,
    output: &Path,
) -> Result<(), AnsysExchangeError> {
    let script = export_pyaedt_script(project);
    std::fs::write(output, script).map_err(|e| AnsysExchangeError::Io(e.to_string()))
}

fn escape_py_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{AnsysDesign, AnsysDesignKind, AnsysProject, AnsysSolutionType};
    use std::collections::BTreeMap;

    #[test]
    fn export_script_contains_hfss_and_q3d_constructors() {
        let mut vars = BTreeMap::new();
        vars.insert("$freq".to_string(), "2.4GHz".to_string());

        let project = AnsysProject {
            name: "DemoProject".to_string(),
            designs: vec![
                AnsysDesign {
                    name: "Antenna".to_string(),
                    kind: AnsysDesignKind::Hfss,
                    solution_type: AnsysSolutionType::DrivenModal,
                    variables: vars,
                },
                AnsysDesign {
                    name: "Interconnect".to_string(),
                    kind: AnsysDesignKind::Q3d,
                    solution_type: AnsysSolutionType::Q3dCg,
                    variables: BTreeMap::new(),
                },
            ],
        };

        let script = export_pyaedt_script(&project);
        assert!(script.contains("from ansys.aedt.core import Hfss, Q3d"));
        assert!(script.contains("Hfss(projectname=\"DemoProject\", designname=\"Antenna\""));
        assert!(script.contains("Q3d(projectname=\"DemoProject\", designname=\"Interconnect\""));
        assert!(script.contains("set_variable(\"$freq\", \"2.4GHz\")"));
    }

    #[test]
    fn export_manifest_json_roundtrip() {
        let project = AnsysProject {
            name: "RoundTrip".to_string(),
            designs: vec![],
        };

        let json = export_manifest_json_string(&project).unwrap();
        let loaded: AnsysProject = serde_json::from_str(&json).unwrap();
        assert_eq!(loaded.name, "RoundTrip");
        assert!(loaded.designs.is_empty());
    }
}
